### ISSUE TITLE
Should not check for allocation completeness

### ISSUE THREAD

**Issue by guillaumejacquart** [abtasty/flagship-js-sdk#7]
In this file, you check whether the total traffic allocation of variation is 100.
This check is incorrect, as variation can have total allocations < 100. In that case, visitor should be untracked (its like he hasn't seen the campaign)

https://github.com/abtasty/flagship-js-sdk/blob/0fd55faf216ba89f79ffde6d98b9a87b8965db30/src/class/bucketingVisitor/bucketingVisitor.ts#L92

**Comment by Emidomenge** [comment]
Fixed, thanks for the feedback :)
